class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start1'
        self.MirrorCommand = 'mirror1'
        self.UnzipMirrorCommand = 'unzipmirror1'
        self.TarMirrorCommand = 'tarmirror1'
        self.CancelMirror = 'cancel1'
        self.CancelAllCommand = 'cancelall1'
        self.ListCommand = 'find1'
        self.StatusCommand = 'status1'
        self.AuthorizedUsersCommand = 'users1'
        self.AuthorizeCommand = 'authorize1'
        self.UnAuthorizeCommand = 'unauthorize1'
        self.AddSudoCommand = 'addsudo1'
        self.RmSudoCommand = 'rmsudo1'
        self.PingCommand = 'ping1'
        self.RestartCommand = 'restart1'
        self.StatsCommand = 'stats1'
        self.HelpCommand = 'help1'
        self.LogCommand = 'log1'
        self.SpeedCommand = 'speedtest1'
        self.CloneCommand = 'clone1'
        self.CountCommand = 'count1'
        self.WatchCommand = 'watch1'
        self.TarWatchCommand = 'tarwatch1'
        self.DeleteCommand = 'del1'
        self.UsageCommand = 'usage1'
        self.MediaInfoCommand = 'mediainfo1'
        self.ConfigMenuCommand = 'config1'
        self.ShellCommand = 'shell1'
        self.UpdateCommand = 'update1'
        self.ExecHelpCommand = 'exechelp1'
        self.TsHelpCommand = 'tshelp1'

BotCommands = _BotCommands()
